// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Regenerate with: dart run tool/generate_windows_zones.dart
// Source: https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-core/supplemental/windowsZones.json

/// The CLDR release [windowsZones] was generated from.
const String windowsZonesCldrVersion = '48';

/// Windows zone key to IANA identifier, CLDR's territory-
/// independent fallback.
const Map<String, String> windowsZones = {
  'AUS Central Standard Time': 'Australia/Darwin',
  'AUS Eastern Standard Time': 'Australia/Sydney',
  'Afghanistan Standard Time': 'Asia/Kabul',
  'Alaskan Standard Time': 'America/Anchorage',
  'Aleutian Standard Time': 'America/Adak',
  'Altai Standard Time': 'Asia/Barnaul',
  'Arab Standard Time': 'Asia/Riyadh',
  'Arabian Standard Time': 'Asia/Dubai',
  'Arabic Standard Time': 'Asia/Baghdad',
  'Argentina Standard Time': 'America/Buenos_Aires',
  'Astrakhan Standard Time': 'Europe/Astrakhan',
  'Atlantic Standard Time': 'America/Halifax',
  'Aus Central W. Standard Time': 'Australia/Eucla',
  'Azerbaijan Standard Time': 'Asia/Baku',
  'Azores Standard Time': 'Atlantic/Azores',
  'Bahia Standard Time': 'America/Bahia',
  'Bangladesh Standard Time': 'Asia/Dhaka',
  'Belarus Standard Time': 'Europe/Minsk',
  'Bougainville Standard Time': 'Pacific/Bougainville',
  'Canada Central Standard Time': 'America/Regina',
  'Cape Verde Standard Time': 'Atlantic/Cape_Verde',
  'Caucasus Standard Time': 'Asia/Yerevan',
  'Cen. Australia Standard Time': 'Australia/Adelaide',
  'Central America Standard Time': 'America/Guatemala',
  'Central Asia Standard Time': 'Asia/Bishkek',
  'Central Brazilian Standard Time': 'America/Cuiaba',
  'Central Europe Standard Time': 'Europe/Budapest',
  'Central European Standard Time': 'Europe/Warsaw',
  'Central Pacific Standard Time': 'Pacific/Guadalcanal',
  'Central Standard Time': 'America/Chicago',
  'Central Standard Time (Mexico)': 'America/Mexico_City',
  'Chatham Islands Standard Time': 'Pacific/Chatham',
  'China Standard Time': 'Asia/Shanghai',
  'Cuba Standard Time': 'America/Havana',
  'Dateline Standard Time': 'Etc/GMT+12',
  'E. Africa Standard Time': 'Africa/Nairobi',
  'E. Australia Standard Time': 'Australia/Brisbane',
  'E. Europe Standard Time': 'Europe/Chisinau',
  'E. South America Standard Time': 'America/Sao_Paulo',
  'Easter Island Standard Time': 'Pacific/Easter',
  'Eastern Standard Time': 'America/New_York',
  'Eastern Standard Time (Mexico)': 'America/Cancun',
  'Egypt Standard Time': 'Africa/Cairo',
  'Ekaterinburg Standard Time': 'Asia/Yekaterinburg',
  'FLE Standard Time': 'Europe/Kiev',
  'Fiji Standard Time': 'Pacific/Fiji',
  'GMT Standard Time': 'Europe/London',
  'GTB Standard Time': 'Europe/Bucharest',
  'Georgian Standard Time': 'Asia/Tbilisi',
  'Greenland Standard Time': 'America/Godthab',
  'Greenwich Standard Time': 'Atlantic/Reykjavik',
  'Haiti Standard Time': 'America/Port-au-Prince',
  'Hawaiian Standard Time': 'Pacific/Honolulu',
  'India Standard Time': 'Asia/Calcutta',
  'Iran Standard Time': 'Asia/Tehran',
  'Israel Standard Time': 'Asia/Jerusalem',
  'Jordan Standard Time': 'Asia/Amman',
  'Kaliningrad Standard Time': 'Europe/Kaliningrad',
  'Korea Standard Time': 'Asia/Seoul',
  'Libya Standard Time': 'Africa/Tripoli',
  'Line Islands Standard Time': 'Pacific/Kiritimati',
  'Lord Howe Standard Time': 'Australia/Lord_Howe',
  'Magadan Standard Time': 'Asia/Magadan',
  'Magallanes Standard Time': 'America/Punta_Arenas',
  'Marquesas Standard Time': 'Pacific/Marquesas',
  'Mauritius Standard Time': 'Indian/Mauritius',
  'Middle East Standard Time': 'Asia/Beirut',
  'Montevideo Standard Time': 'America/Montevideo',
  'Morocco Standard Time': 'Africa/Casablanca',
  'Mountain Standard Time': 'America/Denver',
  'Mountain Standard Time (Mexico)': 'America/Mazatlan',
  'Myanmar Standard Time': 'Asia/Rangoon',
  'N. Central Asia Standard Time': 'Asia/Novosibirsk',
  'Namibia Standard Time': 'Africa/Windhoek',
  'Nepal Standard Time': 'Asia/Katmandu',
  'New Zealand Standard Time': 'Pacific/Auckland',
  'Newfoundland Standard Time': 'America/St_Johns',
  'Norfolk Standard Time': 'Pacific/Norfolk',
  'North Asia East Standard Time': 'Asia/Irkutsk',
  'North Asia Standard Time': 'Asia/Krasnoyarsk',
  'North Korea Standard Time': 'Asia/Pyongyang',
  'Omsk Standard Time': 'Asia/Omsk',
  'Pacific SA Standard Time': 'America/Santiago',
  'Pacific Standard Time': 'America/Los_Angeles',
  'Pacific Standard Time (Mexico)': 'America/Tijuana',
  'Pakistan Standard Time': 'Asia/Karachi',
  'Paraguay Standard Time': 'America/Asuncion',
  'Qyzylorda Standard Time': 'Asia/Qyzylorda',
  'Romance Standard Time': 'Europe/Paris',
  'Russia Time Zone 10': 'Asia/Srednekolymsk',
  'Russia Time Zone 11': 'Asia/Kamchatka',
  'Russia Time Zone 3': 'Europe/Samara',
  'Russian Standard Time': 'Europe/Moscow',
  'SA Eastern Standard Time': 'America/Cayenne',
  'SA Pacific Standard Time': 'America/Bogota',
  'SA Western Standard Time': 'America/La_Paz',
  'SE Asia Standard Time': 'Asia/Bangkok',
  'Saint Pierre Standard Time': 'America/Miquelon',
  'Sakhalin Standard Time': 'Asia/Sakhalin',
  'Samoa Standard Time': 'Pacific/Apia',
  'Sao Tome Standard Time': 'Africa/Sao_Tome',
  'Saratov Standard Time': 'Europe/Saratov',
  'Singapore Standard Time': 'Asia/Singapore',
  'South Africa Standard Time': 'Africa/Johannesburg',
  'South Sudan Standard Time': 'Africa/Juba',
  'Sri Lanka Standard Time': 'Asia/Colombo',
  'Sudan Standard Time': 'Africa/Khartoum',
  'Syria Standard Time': 'Asia/Damascus',
  'Taipei Standard Time': 'Asia/Taipei',
  'Tasmania Standard Time': 'Australia/Hobart',
  'Tocantins Standard Time': 'America/Araguaina',
  'Tokyo Standard Time': 'Asia/Tokyo',
  'Tomsk Standard Time': 'Asia/Tomsk',
  'Tonga Standard Time': 'Pacific/Tongatapu',
  'Transbaikal Standard Time': 'Asia/Chita',
  'Turkey Standard Time': 'Europe/Istanbul',
  'Turks And Caicos Standard Time': 'America/Grand_Turk',
  'US Eastern Standard Time': 'America/Indianapolis',
  'US Mountain Standard Time': 'America/Phoenix',
  'UTC': 'Etc/UTC',
  'UTC+12': 'Etc/GMT-12',
  'UTC+13': 'Etc/GMT-13',
  'UTC-02': 'Etc/GMT+2',
  'UTC-08': 'Etc/GMT+8',
  'UTC-09': 'Etc/GMT+9',
  'UTC-11': 'Etc/GMT+11',
  'Ulaanbaatar Standard Time': 'Asia/Ulaanbaatar',
  'Venezuela Standard Time': 'America/Caracas',
  'Vladivostok Standard Time': 'Asia/Vladivostok',
  'Volgograd Standard Time': 'Europe/Volgograd',
  'W. Australia Standard Time': 'Australia/Perth',
  'W. Central Africa Standard Time': 'Africa/Lagos',
  'W. Europe Standard Time': 'Europe/Berlin',
  'W. Mongolia Standard Time': 'Asia/Hovd',
  'West Asia Standard Time': 'Asia/Tashkent',
  'West Bank Standard Time': 'Asia/Hebron',
  'West Pacific Standard Time': 'Pacific/Port_Moresby',
  'Yakutsk Standard Time': 'Asia/Yakutsk',
  'Yukon Standard Time': 'America/Whitehorse',
};

/// Windows zone key and region to IANA identifier, for the
/// combinations that differ from [windowsZones].
///
/// Keyed `"<zone key>|<region>"`, where the region is what
/// `GetUserDefaultGeoName` returns.
const Map<String, String> windowsZonesByTerritory = {
  'Arab Standard Time|BH': 'Asia/Bahrain',
  'Arab Standard Time|KW': 'Asia/Kuwait',
  'Arab Standard Time|QA': 'Asia/Qatar',
  'Arab Standard Time|YE': 'Asia/Aden',
  'Arabian Standard Time|OM': 'Asia/Muscat',
  'Arabian Standard Time|ZZ': 'Etc/GMT-4',
  'Atlantic Standard Time|BM': 'Atlantic/Bermuda',
  'Atlantic Standard Time|GL': 'America/Thule',
  'Azores Standard Time|GL': 'America/Scoresbysund',
  'Bangladesh Standard Time|BT': 'Asia/Thimphu',
  'Cape Verde Standard Time|ZZ': 'Etc/GMT+1',
  'Central America Standard Time|BZ': 'America/Belize',
  'Central America Standard Time|CR': 'America/Costa_Rica',
  'Central America Standard Time|EC': 'Pacific/Galapagos',
  'Central America Standard Time|HN': 'America/Tegucigalpa',
  'Central America Standard Time|NI': 'America/Managua',
  'Central America Standard Time|SV': 'America/El_Salvador',
  'Central America Standard Time|ZZ': 'Etc/GMT+6',
  'Central Asia Standard Time|AQ': 'Antarctica/Vostok',
  'Central Asia Standard Time|CN': 'Asia/Urumqi',
  'Central Asia Standard Time|IO': 'Indian/Chagos',
  'Central Asia Standard Time|ZZ': 'Etc/GMT-6',
  'Central Europe Standard Time|AL': 'Europe/Tirane',
  'Central Europe Standard Time|CZ': 'Europe/Prague',
  'Central Europe Standard Time|ME': 'Europe/Podgorica',
  'Central Europe Standard Time|RS': 'Europe/Belgrade',
  'Central Europe Standard Time|SI': 'Europe/Ljubljana',
  'Central Europe Standard Time|SK': 'Europe/Bratislava',
  'Central European Standard Time|BA': 'Europe/Sarajevo',
  'Central European Standard Time|HR': 'Europe/Zagreb',
  'Central European Standard Time|MK': 'Europe/Skopje',
  'Central Pacific Standard Time|AQ': 'Antarctica/Casey',
  'Central Pacific Standard Time|FM': 'Pacific/Ponape',
  'Central Pacific Standard Time|NC': 'Pacific/Noumea',
  'Central Pacific Standard Time|VU': 'Pacific/Efate',
  'Central Pacific Standard Time|ZZ': 'Etc/GMT-11',
  'Central Standard Time|CA': 'America/Winnipeg',
  'Central Standard Time|MX': 'America/Matamoros',
  'China Standard Time|HK': 'Asia/Hong_Kong',
  'China Standard Time|MO': 'Asia/Macau',
  'E. Africa Standard Time|AQ': 'Antarctica/Syowa',
  'E. Africa Standard Time|DJ': 'Africa/Djibouti',
  'E. Africa Standard Time|ER': 'Africa/Asmera',
  'E. Africa Standard Time|ET': 'Africa/Addis_Ababa',
  'E. Africa Standard Time|KM': 'Indian/Comoro',
  'E. Africa Standard Time|MG': 'Indian/Antananarivo',
  'E. Africa Standard Time|SO': 'Africa/Mogadishu',
  'E. Africa Standard Time|TZ': 'Africa/Dar_es_Salaam',
  'E. Africa Standard Time|UG': 'Africa/Kampala',
  'E. Africa Standard Time|YT': 'Indian/Mayotte',
  'E. Africa Standard Time|ZZ': 'Etc/GMT-3',
  'Eastern Standard Time|BS': 'America/Nassau',
  'Eastern Standard Time|CA': 'America/Toronto',
  'FLE Standard Time|AX': 'Europe/Mariehamn',
  'FLE Standard Time|BG': 'Europe/Sofia',
  'FLE Standard Time|EE': 'Europe/Tallinn',
  'FLE Standard Time|FI': 'Europe/Helsinki',
  'FLE Standard Time|LT': 'Europe/Vilnius',
  'FLE Standard Time|LV': 'Europe/Riga',
  'GMT Standard Time|ES': 'Atlantic/Canary',
  'GMT Standard Time|FO': 'Atlantic/Faeroe',
  'GMT Standard Time|GG': 'Europe/Guernsey',
  'GMT Standard Time|IE': 'Europe/Dublin',
  'GMT Standard Time|IM': 'Europe/Isle_of_Man',
  'GMT Standard Time|JE': 'Europe/Jersey',
  'GMT Standard Time|PT': 'Europe/Lisbon',
  'GTB Standard Time|CY': 'Asia/Nicosia',
  'GTB Standard Time|GR': 'Europe/Athens',
  'Greenwich Standard Time|BF': 'Africa/Ouagadougou',
  'Greenwich Standard Time|CI': 'Africa/Abidjan',
  'Greenwich Standard Time|GH': 'Africa/Accra',
  'Greenwich Standard Time|GL': 'America/Danmarkshavn',
  'Greenwich Standard Time|GM': 'Africa/Banjul',
  'Greenwich Standard Time|GN': 'Africa/Conakry',
  'Greenwich Standard Time|GW': 'Africa/Bissau',
  'Greenwich Standard Time|LR': 'Africa/Monrovia',
  'Greenwich Standard Time|ML': 'Africa/Bamako',
  'Greenwich Standard Time|MR': 'Africa/Nouakchott',
  'Greenwich Standard Time|SH': 'Atlantic/St_Helena',
  'Greenwich Standard Time|SL': 'Africa/Freetown',
  'Greenwich Standard Time|SN': 'Africa/Dakar',
  'Greenwich Standard Time|TG': 'Africa/Lome',
  'Hawaiian Standard Time|CK': 'Pacific/Rarotonga',
  'Hawaiian Standard Time|PF': 'Pacific/Tahiti',
  'Hawaiian Standard Time|ZZ': 'Etc/GMT+10',
  'Line Islands Standard Time|ZZ': 'Etc/GMT-14',
  'Mauritius Standard Time|RE': 'Indian/Reunion',
  'Mauritius Standard Time|SC': 'Indian/Mahe',
  'Morocco Standard Time|EH': 'Africa/El_Aaiun',
  'Mountain Standard Time|CA': 'America/Edmonton',
  'Mountain Standard Time|MX': 'America/Ciudad_Juarez',
  'Myanmar Standard Time|CC': 'Indian/Cocos',
  'New Zealand Standard Time|AQ': 'Antarctica/McMurdo',
  'Pacific Standard Time|CA': 'America/Vancouver',
  'Romance Standard Time|BE': 'Europe/Brussels',
  'Romance Standard Time|DK': 'Europe/Copenhagen',
  'Romance Standard Time|ES': 'Europe/Madrid',
  'Russian Standard Time|UA': 'Europe/Simferopol',
  'SA Eastern Standard Time|AQ': 'Antarctica/Rothera',
  'SA Eastern Standard Time|BR': 'America/Fortaleza',
  'SA Eastern Standard Time|FK': 'Atlantic/Stanley',
  'SA Eastern Standard Time|SR': 'America/Paramaribo',
  'SA Eastern Standard Time|ZZ': 'Etc/GMT+3',
  'SA Pacific Standard Time|BR': 'America/Rio_Branco',
  'SA Pacific Standard Time|CA': 'America/Coral_Harbour',
  'SA Pacific Standard Time|EC': 'America/Guayaquil',
  'SA Pacific Standard Time|JM': 'America/Jamaica',
  'SA Pacific Standard Time|KY': 'America/Cayman',
  'SA Pacific Standard Time|PA': 'America/Panama',
  'SA Pacific Standard Time|PE': 'America/Lima',
  'SA Pacific Standard Time|ZZ': 'Etc/GMT+5',
  'SA Western Standard Time|AG': 'America/Antigua',
  'SA Western Standard Time|AI': 'America/Anguilla',
  'SA Western Standard Time|AW': 'America/Aruba',
  'SA Western Standard Time|BB': 'America/Barbados',
  'SA Western Standard Time|BL': 'America/St_Barthelemy',
  'SA Western Standard Time|BQ': 'America/Kralendijk',
  'SA Western Standard Time|BR': 'America/Manaus',
  'SA Western Standard Time|CA': 'America/Blanc-Sablon',
  'SA Western Standard Time|CW': 'America/Curacao',
  'SA Western Standard Time|DM': 'America/Dominica',
  'SA Western Standard Time|DO': 'America/Santo_Domingo',
  'SA Western Standard Time|GD': 'America/Grenada',
  'SA Western Standard Time|GP': 'America/Guadeloupe',
  'SA Western Standard Time|GY': 'America/Guyana',
  'SA Western Standard Time|KN': 'America/St_Kitts',
  'SA Western Standard Time|LC': 'America/St_Lucia',
  'SA Western Standard Time|MF': 'America/Marigot',
  'SA Western Standard Time|MQ': 'America/Martinique',
  'SA Western Standard Time|MS': 'America/Montserrat',
  'SA Western Standard Time|PR': 'America/Puerto_Rico',
  'SA Western Standard Time|SX': 'America/Lower_Princes',
  'SA Western Standard Time|TT': 'America/Port_of_Spain',
  'SA Western Standard Time|VC': 'America/St_Vincent',
  'SA Western Standard Time|VG': 'America/Tortola',
  'SA Western Standard Time|VI': 'America/St_Thomas',
  'SA Western Standard Time|ZZ': 'Etc/GMT+4',
  'SE Asia Standard Time|AQ': 'Antarctica/Davis',
  'SE Asia Standard Time|CX': 'Indian/Christmas',
  'SE Asia Standard Time|ID': 'Asia/Jakarta',
  'SE Asia Standard Time|KH': 'Asia/Phnom_Penh',
  'SE Asia Standard Time|LA': 'Asia/Vientiane',
  'SE Asia Standard Time|VN': 'Asia/Saigon',
  'SE Asia Standard Time|ZZ': 'Etc/GMT-7',
  'Singapore Standard Time|BN': 'Asia/Brunei',
  'Singapore Standard Time|ID': 'Asia/Makassar',
  'Singapore Standard Time|MY': 'Asia/Kuala_Lumpur',
  'Singapore Standard Time|PH': 'Asia/Manila',
  'Singapore Standard Time|ZZ': 'Etc/GMT-8',
  'South Africa Standard Time|BI': 'Africa/Bujumbura',
  'South Africa Standard Time|BW': 'Africa/Gaborone',
  'South Africa Standard Time|CD': 'Africa/Lubumbashi',
  'South Africa Standard Time|LS': 'Africa/Maseru',
  'South Africa Standard Time|MW': 'Africa/Blantyre',
  'South Africa Standard Time|MZ': 'Africa/Maputo',
  'South Africa Standard Time|RW': 'Africa/Kigali',
  'South Africa Standard Time|SZ': 'Africa/Mbabane',
  'South Africa Standard Time|ZM': 'Africa/Lusaka',
  'South Africa Standard Time|ZW': 'Africa/Harare',
  'South Africa Standard Time|ZZ': 'Etc/GMT-2',
  'Tokyo Standard Time|ID': 'Asia/Jayapura',
  'Tokyo Standard Time|PW': 'Pacific/Palau',
  'Tokyo Standard Time|TL': 'Asia/Dili',
  'Tokyo Standard Time|ZZ': 'Etc/GMT-9',
  'US Mountain Standard Time|CA': 'America/Creston',
  'US Mountain Standard Time|MX': 'America/Hermosillo',
  'US Mountain Standard Time|ZZ': 'Etc/GMT+7',
  'UTC+12|KI': 'Pacific/Tarawa',
  'UTC+12|MH': 'Pacific/Majuro',
  'UTC+12|NR': 'Pacific/Nauru',
  'UTC+12|TV': 'Pacific/Funafuti',
  'UTC+12|UM': 'Pacific/Wake',
  'UTC+12|WF': 'Pacific/Wallis',
  'UTC+13|KI': 'Pacific/Enderbury',
  'UTC+13|TK': 'Pacific/Fakaofo',
  'UTC-02|BR': 'America/Noronha',
  'UTC-02|GS': 'Atlantic/South_Georgia',
  'UTC-08|PN': 'Pacific/Pitcairn',
  'UTC-09|PF': 'Pacific/Gambier',
  'UTC-11|AS': 'Pacific/Pago_Pago',
  'UTC-11|NU': 'Pacific/Niue',
  'UTC-11|UM': 'Pacific/Midway',
  'W. Central Africa Standard Time|AO': 'Africa/Luanda',
  'W. Central Africa Standard Time|BJ': 'Africa/Porto-Novo',
  'W. Central Africa Standard Time|CD': 'Africa/Kinshasa',
  'W. Central Africa Standard Time|CF': 'Africa/Bangui',
  'W. Central Africa Standard Time|CG': 'Africa/Brazzaville',
  'W. Central Africa Standard Time|CM': 'Africa/Douala',
  'W. Central Africa Standard Time|DZ': 'Africa/Algiers',
  'W. Central Africa Standard Time|GA': 'Africa/Libreville',
  'W. Central Africa Standard Time|GQ': 'Africa/Malabo',
  'W. Central Africa Standard Time|NE': 'Africa/Niamey',
  'W. Central Africa Standard Time|TD': 'Africa/Ndjamena',
  'W. Central Africa Standard Time|TN': 'Africa/Tunis',
  'W. Central Africa Standard Time|ZZ': 'Etc/GMT-1',
  'W. Europe Standard Time|AD': 'Europe/Andorra',
  'W. Europe Standard Time|AT': 'Europe/Vienna',
  'W. Europe Standard Time|CH': 'Europe/Zurich',
  'W. Europe Standard Time|GI': 'Europe/Gibraltar',
  'W. Europe Standard Time|IT': 'Europe/Rome',
  'W. Europe Standard Time|LI': 'Europe/Vaduz',
  'W. Europe Standard Time|LU': 'Europe/Luxembourg',
  'W. Europe Standard Time|MC': 'Europe/Monaco',
  'W. Europe Standard Time|MT': 'Europe/Malta',
  'W. Europe Standard Time|NL': 'Europe/Amsterdam',
  'W. Europe Standard Time|NO': 'Europe/Oslo',
  'W. Europe Standard Time|SE': 'Europe/Stockholm',
  'W. Europe Standard Time|SJ': 'Arctic/Longyearbyen',
  'W. Europe Standard Time|SM': 'Europe/San_Marino',
  'W. Europe Standard Time|VA': 'Europe/Vatican',
  'West Asia Standard Time|AQ': 'Antarctica/Mawson',
  'West Asia Standard Time|KZ': 'Asia/Oral',
  'West Asia Standard Time|MV': 'Indian/Maldives',
  'West Asia Standard Time|TF': 'Indian/Kerguelen',
  'West Asia Standard Time|TJ': 'Asia/Dushanbe',
  'West Asia Standard Time|TM': 'Asia/Ashgabat',
  'West Asia Standard Time|ZZ': 'Etc/GMT-5',
  'West Pacific Standard Time|AQ': 'Antarctica/DumontDUrville',
  'West Pacific Standard Time|FM': 'Pacific/Truk',
  'West Pacific Standard Time|GU': 'Pacific/Guam',
  'West Pacific Standard Time|MP': 'Pacific/Saipan',
  'West Pacific Standard Time|ZZ': 'Etc/GMT-10',
};
