include: package:lints/recommended.yaml

linter:
  rules:
    - comment_references
    - public_member_api_docs
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - use_super_parameters
    - prefer_relative_imports